-- 创建必要的扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector";

-- 创建默认schema
CREATE SCHEMA IF NOT EXISTS public;

-- 授予权限
GRANT ALL PRIVILEGES ON SCHEMA public TO kmap;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kmap;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kmap;

-- 设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO kmap;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO kmap;
